### ISSUE TITLE
Please add this to the Jupyter Community Kernels page

### ISSUE THREAD

**Issue by shamblett** [vickumar1981/jupyter-dart-kernel#11]
I think this should be added to the Jupyter community kernels page [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels). This would give it good visibility to other Dart users who also use Jupyter

**Comment by vickumar1981** [comment]
@shamblett   thanks.  added this repo to the wiki.

**Comment by vickumar1981** [comment]
Added repo to list of jupyter kernels: https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

**Comment by shamblett** [comment]
Excellent, thanks
