### ISSUE TITLE
I have the Error when run any code!

### ISSUE THREAD

**Issue by ali-1989** [vickumar1981/jupyter-dart-kernel#13]
Hi.
my code is:

```
void main(){
  print('hello');
}
```

Window 10
Dart SDK 3.2.2
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : not installed
jupyter_client   : 8.6.0
jupyter_core     : 5.5.0
jupyter_server   : 2.12.1
jupyterlab       : 4.0.9

my error:

'evalue': 'error',
     'output_type': 'error',
     'status': 'error',
     'traceback': ['Could not find a subcommand named "get;" for "dart pub".',
                   '',
                   'Did you mean one of these?',
                   '  get',
                   '',
                   '',
                   'Usage: dart pub [arguments...]',
                   '-h, --help               Print this usage information.',
                   '-v, --verbose            Print detailed logging.',
                   '    --[no-]color         Use colors in terminal output.',
                   '                         Defaults to color when connected to '
                   'a t...',
                   '                         no-color otherwise.',
                   '-C, --directory=<dir>    Run the subcommand in the '
                   'directory<dir...',
                   '                         (defaults to ".")',
                   '',
                   'Available subcommands:',
                   '...16 items truncated...']}

**Comment by vickumar1981** [comment]
@ali-1989 @AnatoliyAksenov 

i think this got introduced in this PR: https://github.com/vickumar1981/jupyter-dart-kernel/pull/12

i went ahead and reverted it for now.

@ali-1989  can you pull the latest from `master` and let me know if this works for you now?

sorry for the delayed response.  work :(.

**Comment by vickumar1981** [comment]
will leave the issue open until it's confirmed/fixed.

**Comment by ali-1989** [comment]
Hi. again. Thanks for reply. I test it and take response.

**Comment by AnatoliyAksenov** [comment]
@ali-1989 Hi
Can you please check if you can do this throw the console?
https://dart.dev/tools/pub/cmd/pub-get

**Comment by ali-1989** [comment]
ok. My problem solved after new clone. Thanks.
