### ISSUE TITLE
Suggestion kernel.json

### ISSUE THREAD

**Issue by T0m6502** [vickumar1981/jupyter-dart-kernel#4]
First, I like to say it's a really nice kernel you made! It saved me a lot of time! 👍 

I am not that experience with Kernels, the comment on the PYTHONPATH really helped me, but I was still struggling. The fix for me was to add this to the json file:

`
	"env": {
		"PYTHONPATH": "<path of dartkernel.py>"
	}
`

Maybe other coders will less struggle upon using this.

Sincerely,
Tom

**Comment by vickumar1981** [comment]
@T0m6502   

good suggestion.  Each person's python path can be different.  It's a user specific setting.  i.e., we can't hard-code the setting in the `kernel.json` file b/c we don't know the location of where the `dartkernel.py` resides (you could have cloned this anywhere, right?)

I think maybe, adding these details to the `README.md` might be sufficient.  

Let me know if there's anything else that's not working.

**Comment by vickumar1981** [comment]
Closing out this issue b/c the setting is user specific.
